### ISSUE TITLE
Game Space crashes

### ISSUE THREAD

**Issue by PycmShoma** [crdroidandroid/android_packages_apps_GameSpace#19]
Process: io.chaldeaprjkt.gamespace
PID: 4546
UID: 1000
Flags: 0x30c8be45
Package: io.chaldeaprjkt.gamespace v32 (12)
Foreground: No
Process-Runtime: 293
Build: Xiaomi/cepheus/cepheus:12/SQ3A.220705.003.A1/1659728653:user/release-keys
Loading-Progress: 1.0

java.lang.RuntimeException: Unable to create service io.chaldeaprjkt.gamespace.gamebar.DanmakuService$Listener: java.lang.IllegalAccessException: java.lang.Class<io.chaldeaprjkt.gamespace.gamebar.DanmakuService$Listener> is not accessible from java.lang.Class<android.app.AppComponentFactory>
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4522)
	at android.app.ActivityThread.access$1700(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2099)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalAccessException: java.lang.Class<io.chaldeaprjkt.gamespace.gamebar.DanmakuService$Listener> is not accessible from java.lang.Class<android.app.AppComponentFactory>
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4491)
	... 9 more

**Comment by neobuddy89** [comment]
This was already fixed in https://github.com/crdroidandroid/android_packages_apps_GameSpace/commit/41467653194b2365f858e68f2dbceea218e94964
